### ISSUE TITLE
Incompatible with voron TAP

### ISSUE THREAD

**Issue by Firas95k** [eamars/VoronPrinterMods#1]
- Hello, thank you for this awesome work, is there any chance you can make this compatible with voron tap?I have switched to voron tap and I got the dragon uhf hotend.

**Comment by eamars** [comment]
Hi @Firas95k Thanks for your feedback. Are you able to give it a go with attached rear mounting piece? 

![image](https://github.com/eamars/VoronPrinterMods/assets/973159/34637a94-67df-40aa-b66f-7422b26419a5)


The rear mounting piece was cut 2mm depth 

Regarding the printability:
First layer
![image](https://github.com/eamars/VoronPrinterMods/assets/973159/d48bc151-d032-44e5-a43e-ef37417d5920)

11th layer
![image](https://github.com/eamars/VoronPrinterMods/assets/973159/eea8fac4-c636-4e2f-b920-5982332b5df1)

In theory it should just work. 

[SBCrazyDragon TH Rear_TAP.zip](https://github.com/eamars/VoronPrinterMods/files/12142772/SBCrazyDragon.TH.Rear_TAP.zip)

Please let me know how it works. If it is proven to work and printable and then I can commit the change with STEP file.

**Comment by eamars** [comment]
Merged in https://github.com/eamars/VoronPrinterMods/pull/3
